name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: make format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run swift-format
          branch: 'main'
